Models/Mahasiswa.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace hello.nett.Models
{
    public class Mahasiswa
    {
        [Required(ErrorMessage = "Nama tidak boleh kosong")]
        public string Nama { get; set; }
        [Required(ErrorMessage = "NIM tidak boleh kosong")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "NIM harus berbentuk angka")]
        public string NIM { get; set; }
        [Required(ErrorMessage = "Angkatan tidak boleh kosong")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Angkatan harus berbentuk angka")]
        public int Angkatan { get; set; }
        [Required(ErrorMessage = "Fakultas tidak boleh kosong")]
        public string Fakultas { get; set; }
    }
}

Controllers/DataTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Collections;

namespace hello.nett.Controllers
{
    public class DataTypeController : Controller
    {
        // GET: DataType
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Array()
        {
            string[] arr = new string[5];
            arr[0] = "Ini adalah teks pertama";
            arr[1] = "Ini adalah teks kedua";
            arr[2] = "Ini adalah teks ketiga";
            arr[3] = "Ini adalah teks keempat";
            arr[4] = "Ini adalah teks kelima";
            ViewBag.Array = arr;
            return View();
        }

        public ActionResult Hashtable()
        {
            Hashtable hashtab = new Hashtable();
            hashtab.Add(1, "Data Pertama");
            hashtab.Add("Dua", 2);
            hashtab.Add('3', true);
            hashtab.Add(false, 'A');
            ViewBag.HashTab = hashtab;
            return View();
        }

        public ActionResult Dictionary()
        {
            Dictionary<string, int> dictionary = new Dictionary<string, int>();
            dictionary.Add("Pertama", 90);
            dictionary.Add("Kedua", 20);
            dictionary.Add("Ketiga", 37);
            dictionary.Add("Keempat", 49);
            ViewBag.Dict = dictionary;
            return View();
        }

        public ActionResult List()
        {
            List<string> list = new List<string>();
            list.Add("ini list pertama");
            list.Add("ini list kedua");
            list.Add("ini list ketiga");
            list.Add("ini list keempat");
            ViewBag.List = list;
            return View();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace hello.nett.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/MahasiswaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using hello.nett.Models;

namespace hello.nett.Controllers
{
    public class MahasiswaController : Controller
    {
        // GET: Mahasiswa
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(Mahasiswa mahasiswa)
        {
            if (!ModelState.IsValid)
                return View();
            return View("index", mahasiswa);
        }
    }
}

Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace hello.nett.Controllers
{
    public class ProfileController : Controller
    {
        // GET: Profile
        public ActionResult Index()
        {
            return View();
        }
    }
}

Views/DataType/Array.cshtml
@{
    ViewBag.Title = "Array";
}

<h2>Array</h2>
<div>
    @for (var i =0; i < ViewBag.Array.Length; i++)
            {
                <div> Isi array ke @(i+1) = @ViewBag.Array[i] </div>
            }
</div>

Views/DataType/Dictionary.cshtml
@{
    ViewBag.Title = "Dictionary";
    var dict = ViewBag.Dict as Dictionary<string, int>;
}

<h2>Dictionary</h2>
<div>
    @foreach (var i in dict)
    {
        <div> Dictionary dengan key "@i.Key" memiliki value = @i.Value</div>
    }
    <br />
    <div>
        Test untuk menggunakan key "Pertama" : @dict["Pertama"]
    </div>
</div>

Views/DataType/Hashtable.cshtml
@{
    ViewBag.Title = "Hashtable";
}

<h2>Hashtable</h2>
<div>
    @foreach (var ht in ViewBag.HashTab)
    {
        <div> Hashtable dengan key @ht.Key  memiliki value @ht.Value </div>
    }
    <br />
    Cek Hashtable dengan key False : @ViewBag.HashTab[false]
</div>

Views/DataType/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Data Type</h2>
<p class="lead">Kumpulan tipe data</p>
@Html.ActionLink("Array", "Array", "DataType", null, new { @style = "text-decoration:none;color:white;background-color:grey;padding:10px 40px;border-radius:5px;" })
@Html.ActionLink("List", "List", "DataType", null, new { @style = "text-decoration:none;color:white;background-color:grey;padding:10px 40px;border-radius:5px;" })
@Html.ActionLink("Dictionary", "Dictionary", "DataType", null, new { @style = "text-decoration:none;color:white;background-color:grey;padding:10px 40px;border-radius:5px;" })
@Html.ActionLink("Hashtable", "Hashtable", "DataType", null, new { @style = "text-decoration:none;color:white;background-color:grey;padding:10px 40px;border-radius:5px;" })

Views/DataType/List.cshtml
@{
    ViewBag.Title = "List";
}

<h2>List</h2>
<div>
    @{ 
        var i = 1;
    }
    @foreach (var list in ViewBag.List)
    {
        <div> list ke-@(i++) : @list </div>
    }
</div>

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Test</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Views/Mahasiswa/Index.cshtml
@model hello.nett.Models.Mahasiswa
@{
    ViewBag.Title = "Index";
}

<h1>Mahasiswa</h1>
<p style="color:grey;font-size:15px">List Mahasiswa</p>
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#modal">
    Add Data Mahasiswa
</button>
<div class="modal fade" id="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Tambah Mahasiswa</h4>
            </div>
            @using (Html.BeginForm("Index", "Mahasiswa", FormMethod.Post))
            {
                @Html.ValidationSummary()
                <div class="modal-body">
                    <div class="form-group">
                        <label for="exampleInputEmail1">Nama</label>
                        @Html.TextBoxFor(x => x.Nama, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">NIM</label>
                        @Html.TextBoxFor(x => x.NIM, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Angkatan</label>
                        @Html.TextBoxFor(x => x.Angkatan, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Fakultas</label>
                        @Html.TextBoxFor(x => x.Fakultas, new { @class = "form-control" })
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Add Data</button>
                </div>
            }
        </div>
    </div>
</div>
@if (Model != null)
{
    <h3>Data Berhasil Dimasukkan !</h3>
    <div class="row">
        <div class="col-sm-12">
            <div class="col-sm-3"> Nama </div>
            <div class="col-sm-1"> : </div>
            <div class="col-sm-8">@Model.Nama</div>
        </div>
        <div class="col-sm-12">
            <div class="col-sm-3"> NIM </div>
            <div class="col-sm-1"> : </div>
            <div class="col-sm-8">@Model.NIM</div>
        </div>
        <div class="col-sm-12">
            <div class="col-sm-3"> Angkatan </div>
            <div class="col-sm-1"> : </div>
            <div class="col-sm-8">@Model.Angkatan</div>
        </div>
        <div class="col-sm-12">
            <div class="col-sm-3"> Fakultas </div>
            <div class="col-sm-1"> : </div>
            <div class="col-sm-8">@Model.Fakultas</div>
        </div>
    </div>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Profile", "Index", "Profile")</li>
                    <li>@Html.ActionLink("Data Type", "Index", "DataType")</li>
                    <li>@Html.ActionLink("Mahasiswa", "Index", "Mahasiswa")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>